// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lahkiuxwyzctdzcpmcim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhaGtpdXh3eXpjdGR6Y3BtY2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjcyNDcsImV4cCI6MjA2OTQ0MzI0N30.EyCrkZB4c6Jj-iWa7Lm1LsrxmYTcpnrQQlVQ4rUUBtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});